version: '3.8'

services:
  email-api:
    build:
        context: .
        dockerfile: Dockerfile-local
    container_name: devTTMailSender_api
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/api
      - ~/.m2:/root/.m2
    ports:
      - "35730:35729"
      - "5006:5005"
    networks:
      devTT_network:
        aliases:
          - email-api

networks:
  devTT_network:
    external: true